### ISSUE TITLE
audio button icon not shown

### ISSUE THREAD

**Issue by emacsbliss** [condy0919/fanyi.el#17]
maybe it's the font I'm using cause this issue? Currently I'm using Jetbrains mono, the icon where we click to play sound shows blank in my emacs.

**Comment by condy0919** [comment]
Most audio buttons use emoji ('🔊').

> "C-x 8 RET 1f50a" or "C-x 8 RET SPEAKER WITH THREE SOUND WAVES"

to check whether it's displayed in tofu or not.

Emacs will use symbola if no font is found to display emoji. If you use archlinux,

``` shell
yay -S ttf-symbola
```

**Comment by emacsbliss** [comment]
thanks for the info. C-x 8 RET shows blank for this emoji.

also I'm on Mac, seems no ttf-symbola for it..

**Comment by condy0919** [comment]
You can use "Apple Color Emoji" to display emoji.

``` emacs-lisp
;; Emacs 29, 28
(set-fontset-font t 'emoji (font-spec :family "Apple Color Emoji") nil 'prepend)

;; Emacs 27
(set-fontset-font t 'symbol (font-spec :family "Apple Color Emoji") nil 'prepend)
```

**Comment by emacsbliss** [comment]
great, that works!! thanks a lot!
maybe add this to readme might help others too.
