### ISSUE TITLE
建议查词结果buffer保持开启，但焦点仍在阅读buffer里

### ISSUE THREAD

**Issue by heisaari** [condy0919/fanyi.el#27]
很好的插件，nice

左右分屏查词时，如左边是文章，右边是查词结果，阅读时希望保持焦点在左侧，遇到生词时查一下，继续阅读再查另一个，来回跳转有点分神

**Comment by condy0919** [comment]
谢谢建议！

**Comment by condy0919** [comment]
https://github.com/condy0919/fanyi.el/commit/2c3193e080e04ee1d966ecca89ac5ddfc7a42599

将 `fanyi-auto-select` 设置为 `nil` 就行。

**Comment by heisaari** [comment]
(defcustom fanyi-auto-select nil
  "Non-nil means select fanyi window."
  :type 'boolean
  :group 'fanyi)
linux下，改过了仍然不行

**Comment by condy0919** [comment]
> (defcustom fanyi-auto-select nil "Non-nil means select fanyi window." :type 'boolean :group 'fanyi) linux下，改过了仍然不行

试着这样排查一下:

```shell
# 修正一下这里 s 和 fanyi 目录的路径
emacs -Q -L ~/.emacs.d/elpa/s -L ~/.emacs.d/elpa/fanyi
```

然后再 <kbd>M-:</kbd> `(setq fanyi-auto-select)` 即可。

我本地测试没问题。

**Comment by heisaari** [comment]
@condy0919 
![111](https://user-images.githubusercontent.com/108096168/181247895-8941b729-756c-45d5-81a5-032cff6d5ecf.png)

**Comment by condy0919** [comment]
> @condy0919 照做了，但不会排查
> ![111](https://user-images.githubusercontent.com/108096168/181247895-8941b729-756c-45d5-81a5-032cff6d5ecf.png)
> 
> 

你把 t 放在右括号外面了..

**Comment by heisaari** [comment]
> 

@condy0919 
![fff](https://user-images.githubusercontent.com/108096168/181605309-529807e9-e4ee-4f56-936a-eeaa62dd7f9a.png)
我晕了，只改动了一处，t 变成 nil，这个什么 t 在括号外是还需要在哪里找呢
试着删除了fanyi，重新安装，只改 t 为 nil，结果也是一样

**Comment by condy0919** [comment]
啊，不好意思。我才看到是我的复现例子有点问题，应该是 M-:  `(setq fanyi-auto-select nil)`.

您再照着

> > (defcustom fanyi-auto-select nil "Non-nil means select fanyi window." :type 'boolean :group 'fanyi) linux下，改过了仍然不行
> 
> 试着这样排查一下:
> 
> ```shell
> # 修正一下这里 s 和 fanyi 目录的路径
> emacs -Q -L ~/.emacs.d/elpa/s -L ~/.emacs.d/elpa/fanyi
> ```
> 
> 然后再 M-: `(setq fanyi-auto-select nil)` 即可。
> 
> 我本地测试没问题。

这里测试可以复现吗？

**Comment by heisaari** [comment]
> 啊，不好意思。我才看到是我的复现例子有点问题，应该是 M-: `(setq fanyi-auto-select nil)`.
> 
> 您再照着
> 
> > > (defcustom fanyi-auto-select nil "Non-nil means select fanyi window." :type 'boolean :group 'fanyi) linux下，改过了仍然不行
> > 
> > 
> > 试着这样排查一下:
> > ```shell
> > # 修正一下这里 s 和 fanyi 目录的路径
> > emacs -Q -L ~/.emacs.d/elpa/s -L ~/.emacs.d/elpa/fanyi
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 然后再 M-: `(setq fanyi-auto-select nil)` 即可。
> > 我本地测试没问题。
> 
> 这里测试可以复现吗？

![yyy](https://user-images.githubusercontent.com/108096168/181622755-4bef0af4-430d-427d-8258-dabdd28d5e43.png)
返回一个nil

**Comment by condy0919** [comment]
> 想尝试在这个emacs里执行m-x fanyi-dwim2好像不行所以没试成

这里为什么没有成功呢？

**Comment by heisaari** [comment]
> > 想尝试在这个emacs里执行m-x fanyi-dwim2好像不行所以没试成
> 
> 这里为什么没有成功呢？

因为显示No match，手工打上命令也是No match执行不了

**Comment by condy0919** [comment]
> > > 想尝试在这个emacs里执行m-x fanyi-dwim2好像不行所以没试成
> > 
> > 这里为什么没有成功呢？
> 
> 因为显示No match，手工打上命令也是No match执行不了

需要你

```elisp
(require 'fanyi)
```

一下

**Comment by heisaari** [comment]
感谢指导，这样测试没问题，那看来要排查init里的内容了

**Comment by condy0919** [comment]
> 感谢指导，这样测试没问题，那看来要排查init里的内容了

我觉得你是用了 shackle/popup/popper 之类的插件吧，检查一下这个部分就可以了。例如 https://github.com/seagle0128/.emacs.d/blob/master/lisp/init-window.el#L182
